name: Generate PDF report

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pandoc and TeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Generate PDF from README_REPORT.md
        run: |
          pandoc README_REPORT.md -o README_REPORT.pdf

      - name: Upload README_REPORT.pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: README_REPORT.pdf
          path: README_REPORT.pdf
